<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[11]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[10]=array(0,1,1,'5LiT6aKY5rS75Yqo');
$cfg_Cs[9]=array(0,1,1,'5Y+M5Z2H5Yqo5oCB');
$cfg_Cs[8]=array(0,1,1,'5Y+M5Z2H5Yy75biI');
$cfg_Cs[7]=array(0,1,1,'5Y+M5Z2H5ZOB54mM');
$cfg_Cs[12]=array(0,1,1,'5Y+M5Z2H6aG555uu');
$cfg_Cs[13]=array(12,1,1,'55qu6IKk576O5a65');
$cfg_Cs[14]=array(12,1,1,'57q557uj576O5a65');
$cfg_Cs[15]=array(12,1,1,'5rOo5bCE576O5a65');
$cfg_Cs[16]=array(12,1,1,'5ZC46ISC55im6Lqr');
$cfg_Cs[17]=array(12,1,1,'57Sn6IKk6Zmk55qx');
$cfg_Cs[18]=array(0,1,1,'5Y+M5Z2H5Zyw5Zu+');
$cfg_Cs[20]=array(0,1,1,'5LiT6aKY');
?>