<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('114', '/uploads/allimg/160504/1-1605041055060-L.jpg');
$maNum = 1;
$myaddons[$maNum] = array('115', '/uploads/allimg/160504/10551L946-0.jpg');
$maNum = 2;
$myaddons[$maNum] = array('116', '/uploads/allimg/160504/10551J520-1.jpg');
$maNum = 3;
$myaddons[$maNum] = array('117', '/uploads/allimg/160504/10551M922-2.jpg');
$maNum = 4;
$myaddons[$maNum] = array('118', '/uploads/allimg/160504/10551KR0-3.jpg');
$maNum = 5;
$myaddons[$maNum] = array('119', '/uploads/allimg/160504/10551K560-4.jpg');
$maNum = 6;
$myaddons[$maNum] = array('120', '/uploads/allimg/160504/10551L432-5.jpg');
$maNum = 7;
