<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('1054', '/uploads/allimg/160515/1-1605151S641241.jpg');
$maNum = 1;
$myaddons[$maNum] = array('1055', '/uploads/allimg/160515/1-1605151SKO93.jpg');
$maNum = 2;
$myaddons[$maNum] = array('1056', '/uploads/allimg/160515/1-1605151SU3958.jpg');
$maNum = 3;
$myaddons[$maNum] = array('1057', '/uploads/allimg/160515/1-1605151T142942.jpg');
$maNum = 4;
