<?php
$z[0]=Array("field","",31,59);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",61,90);
$z[1][4]['name']="typename";
$z[2]=Array("field","",104,132);
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\r\n			<li>\r\n				<span class=\"date\">[field:pubdate function=\"MyDate('m-d',@me)\"/]</span>\r\n				<a href=\"[field:arcurl /]\">[field:title /]</a>\r\n			</li>\r\n			",146,350);
$z[3][4]['titlelen']="60";
$z[3][4]['row']="8";
$z[4]=Array("field","",359,388);
$z[4][4]['name']="typename";
$z[5]=Array("arclist","\r\n			<li>\r\n				<a  href=\"[field:linkurl/]\">\r\n					<!--  封面  -->\r\n					<img src=\"[field:cover_img/] \" width=\"202px\" height=\"317px\"/>	\r\n				</a>\r\n				<div class=\"erwei\">\r\n					<!-- 二维码图片 -->\r\n					<img src=\"[field:erwei_img/] \" width=\"170\" />	\r\n				</div>\r\n				<h2>[field:title /]</h2>\r\n				<a href=\"[field:arcurl/]\" title=\"[field:fulltitle /] \" class=\"btn_video\">点阅</a>\r\n			</li>\r\n		",425,886);
$z[5][4]['addfields']="jiage";
$z[5][4]['channelid']="2";

?>