<div class="n_xwzt_article_list clearfix">
              [field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<a target='_blank' href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>"); [/field:array]
              <div>
                <h2><a href="[field:arcurl/]" class="title" target="_blank">[field:title/]</a></h2>
                <p class="content">[field:description/]... </p>
                <p class="pubdate">[field:pubdate function="GetDateMK(@me)"/]</p>
              </div>
            </div>