{dede:field name='typeurl'/}
				{dede:field name='typename'/}
					
				<div class="bg12 news_year">
					<div class="ctablk news size4 year first_child" style="opacity: 1;">
						<div class="container trans">
							<img src="{dede:field.typeimg /}" width="290px" height="112px"/>
						</div>
					</div>
					<div class="ctablk news left ">
						<div class="wr">
							<div class="container trans">
								<a class="homenewslink" href="/ttas/pp/733.html" title="【跨界荣誉】Yestar艺星整形荣获2015-2016OnlyLady美容">
									<div class="georgia-title">
										<h3>
											<div style="margin: 0px; padding: 0px; border: 0px none;">【跨界荣誉】Yestar艺星整形荣获201</div>
										</h3>
										<i class="sprite-h gtitle-deco below"></i>
									</div>
									<p>3月28日晚，2015-2016OnlyLady美容天后颁奖盛典在上海外滩举行，美丽高贵的胡杏</p>
									<div class="cta">
										<div>
											<span class="label">阅读</span>
										</div>
									</div>

									<div class="visu">
										<img style="display: inline;" src="{dede:global.cfg_medias_dir/}/static/zixun/images/1-1603291J4264Q-lp.jpg" width="289px" height="180px"></div>
								</a>
							</div>
						</div>
					</div>

					<div class="clear"></div>
				</div>