<div class="ctablk news left ">
						<div class="wr">
							<div class="container trans">
								<a class="homenewslink" href="[field:arcurl/]" title="[field:fulltitle/]">
									<div class="georgia-title">
										<h3>
											<div style="margin: 0px; padding: 0px; border: 0px none;">[field:infos/]</div>
										</h3>
										<i class="sprite-h gtitle-deco below"></i>
									</div>
									<p>[field:description/]</p>
									<div class="cta">
										<div>
											<span class="label">阅读</span>
										</div>
									</div>

									<div class="visu">
										<img style="display: inline;" src="{dede:global.cfg_medias_dir/}/static/zixun/images/1-1603291J4264Q-lp.jpg" width="289px" height="180px"></div>
								</a>
							</div>
						</div>
					</div>

					<div class="clear"></div>
				</div>