<?php
$z[0]=Array("global","",46,78);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("field","",96,117);
$z[1][4]['name']="typeid";
$z[2]=Array("field","",153,181);
$z[2][4]['name']="typeurl";
$z[3]=Array("field","",199,228);
$z[3][4]['name']="typename";
$z[4]=Array("field","",241,269);
$z[4][4]['name']="typeurl";
$z[5]=Array("field","",340,368);
$z[5][4]['name']="typeurl";
$z[6]=Array("field","",386,441);
$z[6][4]['name']="description";
$z[6][4]['function']="cn_substr(@me,170)";
$z[7]=Array("arclist","\r\n                <li><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></li>\r\n                ",525,676);
$z[7][4]['infolen']="20";
$z[7][4]['row']="3";

?>