 

    <div class="size1 ctablk left ">
		<div class="wr">
			<div class="container trans">
				<a href='[field:typeurl function='str_replace("index.html","",@me)'/]'>
					<i class="sprite-h gtitle-deco"></i>
					<div class="s_desc">
						<h2>[field:typename/]</h2>
						<!--<h3>쌍꺼풀</h3>-->
					</div>
					<div class="cta">
						<div><span class="label">探索</span></div>
					</div>




					<div class="visu"> <img src='{dede:field.typelitpic/}' width="211px" height="253px" class="anim"> </div>
				</a>
			</div>
		</div>
	</div>


    

<li><a href='[field:typeurl function='str_replace("index.html","",@me)'/]'>[field:typename/]</a></li> 
