<?php
$z[0]=Array("field","",41,57);
$z[0][4]['name']="id";
$z[1]=Array("arclist","\r\n					<h2><a href=\"[field:arcurl/]\" target=\"_blank\">[field:fulltitle/]</a></h2>\r\n					<p>[field:info/]...<a href=\"[field:arcurl/]\" target=\"_blank\">[详情]</a></p>\r\n					",103,337);
$z[1][4]['att']="h";
$z[1][4]['limit']="0,1";
$z[1][4]['infolen']="230";
$z[2]=Array("arclist","\r\n					<li><a href=\"[field:arcurl/]\" target=\"_blank\">[field:fulltitle/]</a></li>\r\n					",381,531);
$z[2][4]['att']="h";
$z[2][4]['limit']="1,5";
$z[2][4]['infolen']="230";
$z[3]=Array("arclist","\r\n					<li><a href=\"[field:arcurl/]\" target=\"_blank\">[field:fulltitle/]</a></li>\r\n					",574,724);
$z[3][4]['att']="h";
$z[3][4]['limit']="5,5";
$z[3][4]['infolen']="230";

?>