<?php
$z[0]=Array("field","",159,181);
$z[0][4]['name']="typeimg";
$z[1]=Array("arclist","\r\n\r\n					<div class=\"ctablk news left \">\r\n						<div class=\"wr\">\r\n							<div class=\"container trans\">\r\n								<a class=\"homenewslink\" href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\">\r\n									<div class=\"georgia-title\">\r\n										<h3>\r\n											<div style=\"margin: 0px; padding: 0px; border: 0px none;\">[field:title/]</div>\r\n										</h3>\r\n										<i class=\"sprite-h gtitle-deco below\"></i>\r\n									</div>\r\n									<p>[field:infos/]</p>\r\n									<div class=\"cta\">\r\n										<div>\r\n											<span class=\"label\">阅读</span>\r\n										</div>\r\n									</div>\r\n\r\n									<div class=\"visu\">\r\n										<img style=\"display: inline;\" src=\"[field:picname/]\" width=\"289px\" height=\"180px\"></div>\r\n								</a>\r\n							</div>\r\n						</div>\r\n					</div>\r\n\r\n					<div class=\"clear\"></div>\r\n				</div>\r\n\r\n		",247,1106);
$z[1][4]['infolen']="100";

?>