<div class="blk top-news subactu tmpblk">
  <a href="/zixun/">
    <span class="ttl">
      &#26368;&#26032;&#36164;&#35759; <i class="sprite-h checkerboard below"></i>
    </span>
  </a>
  <a href="[field:arcurl/]" class="last">
    <div class="visu">
      <img src="[field:picname/]"></div>
    <div class="h3 ajax"> <b>[field:title/]</b>
    </div>
    <p class="ajax">[field:infos/]</p>
  </a> <i class="sprite-h gtitle-deco above"></i>
  <a href="/zixun/" class="all"> <strong>查看更多资讯</strong>
  </a>
</div>