<div class="tsfw_list">
    <div class="tsfw_list_left">
      <a href="[field:arcurl/]"><img src="[field:picname/]" /></a>
    </div>
    <div class="tsfw_list_right">
      <div class="right_tm">
	    <p><a href="[field:arcurl/]">[field:fulltitle/]</a></p>
	    <p>[field:infos/]</p>
	  </div>
	  <div class="right_zx">
	    <ul>
	      <li><a href="[field:arcurl/]">了解详情</a></li>
	      <li><a href="#">在线咨询</a></li>
	      <li><a href="#">预约挂号</a></li>
	    </ul>
	  </div>
    </div>
  </div>