<li>
					<div [field:global function=MagicVar("class='left ic_desc'","class='left ic_img'")/]>
						<div class="item_nav_tit">
							<h1>[field:title/]</h1>
							<span></span>
							<span>蝶变感受：</span>
							<p>[field:description/]</p>
						</div>
						<a href="[field:arcurl/]" target="_blank" class="btn_box">更多详情</a>
					</div>
					<div class="right ic_img">
						<img src="[field:picname/]"  width="600px" height="635px"/>				
					</div>
					<div class="clear"></div>
				</li>