<div class="size1 ctablk left ">
		<div class="wr">
			<div class="container trans">
				<a href="{dede:field name='typeurl'/}">
					<i class="sprite-h gtitle-deco"></i>
					<div class="s_desc">
						<h2>{dede:field name='typename'/}</h2>
						
					</div>
					<div class="cta">
						<div><span class="label">探索</span></div>
					</div>
					<div class="visu"> <img src="{dede:field.typeimg /}" width="211px" height="253px" class="anim"> </div>
				</a>
			</div>
		</div>
	</div>