<?php
$z[0]=Array("field","",4,33);
$z[0][4]['name']="typename";
$z[1]=Array("php","echo 1;{dede:php",63,91);
$z[2]=Array("arclist","\r\n			<li>\r\n				<a  href=\"[field:linkurl/]\">\r\n					<!--  封面  -->\r\n					<img src=\"[field:cover_img/] \" width=\"202px\" height=\"317px\"/>\r\n				</a>\r\n				<div class=\"erwei\">\r\n					<!-- 二维码图片 -->\r\n					<img src=\"[field:erwei_img/] \" width=\"170\" />	\r\n				</div>\r\n				<h2>[field:title /]</h2>\r\n				<a href=\"[field:linkurl/]\" title=\"[field:fulltitle /] \" class=\"btn_video\">点阅</a>\r\n			</li>\r\n		",97,583);
$z[2][4]['addfields']="cover_img,erwei_img,linkurl";
$z[2][4]['channelid']="19";

?>