<div class="n_xwzt_recommend">
              [field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<img src='{@me['litpic']}'/>"); [/field:array]
              <div class="mask">
                <h3><a href="[field:arcurl/]" target="_blank">[field:title/]</a></h3>
                <span><a href="[field:arcurl/]" target="_blank">[field:info/]</a></span>
              </div>
            </div>