<?php
$z[0]=Array("global","",36,68);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",86,110);
$z[1][4]['name']="itemindex";
$z[2]=Array("field","",123,152);
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n			<li><a href=\"[field:typelink/]\">[field:typename/]</a><img src=\"[field:global.cfg_templets_skin/]/imgs/n_side_arrow.png\" /></li>\r\n			",194,384);
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>