<field:zt_img itemname="专题图片" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zt_img>
<field:zt_title itemname="专题标题" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zt_title>
<field:zt_smalltext itemname="专题简介" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zt_smalltext>

<field:zt_url itemname="链接地址" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zt_url>

<field:zt_body itemname="专题内容" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zt_body>

