<field:zw itemname="职务" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zw>
<field:ziwei itemname="职位" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:ziwei>
<field:scxm itemname="擅长项目" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:scxm>
<field:zyll itemname="主要履历" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zyll>
<field:ystp itemname="医生图片" autofield="1" notsend="0" type="img" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:ystp>
