<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	
<field:doctor_img itemname="专家轮播图" autofield="1" notsend="0" type="imgfile" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:doctor_img>


<field:doctor_zhiwei itemname="职位" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:doctor_zhiwei>

<field:doctor_yingwen itemname="英文名" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:doctor_yingwen>

<field:doctor_touxian itemname="头衔" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:doctor_touxian>

<field:doctor_shanchang itemname="擅长项目" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="2500" page="">
</field:doctor_shanchang>

<field:doctor_lvli itemname="主要履历" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="2500" page="">
</field:doctor_lvli>

<field:doctor_yuantu itemname="专家圆图" autofield="1" notsend="0" type="imgfile" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:doctor_yuantu>
