<li class="active" style="z-index:0;opacity:0;">
                            <a href="[field:arcurl/]" title="[field:title/]" class="izd"><img src="[field:litpic/]" alt="[field:title/]" /></a>
                            <div class="izz">
                    <div class="izh"><span>[field:title/]</span>   [field:doctor_zhiwei/]</div>
                    <div class="izp">[field:doctor_yingwen/]</div>
                    <div class="izy">([field:doctor_touxian/])</div>
                    <div class="izj izjb">
                        <div class="izjt">擅长项目：</div>
                        [field:doctor_shanchang/]
                    </div>
                    <div class="izj">
                        <div class="izjt">主要履历：</div>
                        [field:doctor_lvli/]...
                    </div>
               <a href="[field:arcurl/]" title="了解详情" class="izza izzafirst"><img src="{dede:global.cfg_templets_skin/}/images/izl.jpg" alt="了解详情" /></a>
               <a href="http://pdt.zoosnet.net/LR/Chatpre.aspx?id=PDT21034666&lng=cn" class="izza" title="在线咨询"><img src="{dede:global.cfg_templets_skin/}/images/izj.jpg" alt="在线咨询" /></a>
               <a href="http://pdt.zoosnet.net/LR/Chatpre.aspx?id=PDT21034666&lng=cn" class="izza" title="预约挂号"><img src="{dede:global.cfg_templets_skin/}/images/izg.jpg" alt="预约挂号" /></a>    
                </div>
                  </li>