<?php
$z[0]=Array("arcurl","",87,102);
$z[1]=Array("title","",111,125);
$z[2]=Array("litpic","",149,164);
$z[3]=Array("title","",171,185);
$z[4]=Array("title","",285,299);
$z[5]=Array("doctor_zhiwei","",309,331);
$z[6]=Array("doctor_yingwen","",376,399);
$z[7]=Array("doctor_touxian","",445,468);
$z[8]=Array("doctor_shanchang","",610,635);
$z[9]=Array("doctor_lvli","",793,813);
$z[10]=Array("arcurl","",870,885);

?>