
<field:zt_url itemname="链接地址" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="" color="#CF2222">
</field:zt_url>
<field:zt_pic itemname="专题图片" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="" color="#CF2222" >
</field:zt_pic>
<field:zt_body itemname="专题内容" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zt_body>
