<field:cover_img itemname="封面图片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="1" default=""  maxlength="250" page="" style="color:#CE2222">
</field:cover_img>
<field:erwei_img itemname="二维码图片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="1" default=""  maxlength="250" page="" style="color:#CE2222">
</field:erwei_img>
<field:linkurl itemname="外链地址" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="" style="color:#CE2222">
</field:linkurl>
