<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",387,424);
$z[2][4]['filename']="header.htm";
$z[3]=Array("global","",490,522);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("field","",791,809);
$z[4][4]['name']="body";
$z[5]=Array("include","",850,887);
$z[5][4]['filename']="footer.htm";

?>