<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",387,425);
$z[2][4]['filename']="header2.htm";
$z[3]=Array("field","",690,712);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n<dd><a href='[field:typelink/]'>[field:typename/]</a></dd>\r\n",758,873);
$z[4][4]['type']="son";
$z[4][4]['typeid']="610";
$z[5]=Array("field","",978,996);
$z[5][4]['name']="body";
$z[6]=Array("include","",1039,1076);
$z[6][4]['filename']="footer.htm";

?>