<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",379,416);
$z[2][4]['filename']="header.htm";
$z[3]=Array("field","",2563,2585);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n<dd><a href='[field:typelink/]'>[field:typename/]</a></dd>\r\n",2631,2746);
$z[4][4]['type']="son";
$z[4][4]['typeid']="609";
$z[5]=Array("field","",2857,2876);
$z[5][4]['name']="title";
$z[6]=Array("field","",3014,3066);
$z[6][4]['name']="pubdate";
$z[6][4]['function']="MyDate('Y-m-d',@me)";
$z[7]=Array("field","",3201,3228);
$z[7][4]['name']="phpurl";
$z[8]=Array("field","",3252,3275);
$z[8][4]['name']="id";
$z[9]=Array("field","",3280,3304);
$z[9][4]['name']="mid";
$z[10]=Array("field","",3481,3499);
$z[10][4]['name']="body";
$z[11]=Array("prenext","",3529,3554);
$z[11][4]['get']="pre";
$z[12]=Array("prenext","",3584,3610);
$z[12][4]['get']="next";
$z[13]=Array("arclist","\r\n<li><a href='[field:arcurl/]' target=\"_blank\">[field:title/]</a></li>\r\n",3674,3799);
$z[13][4]['row']="5";
$z[13][4]['orderby']="rand";
$z[14]=Array("channelartlist","\r\n<li>\r\n<dt><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></dt>\r\n{dede:arclist titlelen='21' row='10'}\r\n<dd><a href=\"[field:arcurl /]\">[field:title /]</a></dd>\r\n{/dede:arclist}\r\n<div style=\"clear:both;\"></div>\r\n</li>\r\n",3930,4230);
$z[14][4]['typeid']="614";
$z[15]=Array("include","",4339,4376);
$z[15][4]['filename']="footer.htm";

?>