 

    <div class="size1 ctablk left ">
		<div class="wr">
			<div class="container trans">
				<a href='[field:typeurl function='str_replace("index.html","",@me)'/]'>
					<i class="sprite-h gtitle-deco"></i>
					<div class="s_desc">
						<h2>[field:typename/]</h2>
						<!--<h3>쌍꺼풀</h3>-->
					</div>
					<div class="cta">
						<div><span class="label">探索</span></div>
					</div>

					<div class="visu"> <img src='[field.seotitle/]' width="211px" height="253px" class="anim"> </div>
					<div>{dede:sql sql='Select content from dede_arctype where id=4'}

[field:content/]

{/dede:sql}</div>
				</a>
			</div>
		</div>
	</div>

