{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='' text='' width='978' height='619'} /uploads/allimg/2016-05/15152551-1-19294.jpg {/dede:img}
{dede:img ddimg='' text='' width='978' height='619'} /uploads/allimg/2016-05/15152551-1-29194.jpg {/dede:img}
{dede:img ddimg='' text='' width='978' height='619'} /uploads/allimg/2016-05/15152551-1-35247.jpg {/dede:img}
{dede:img ddimg='' text='' width='978' height='619'} /uploads/allimg/2016-05/15152551-1-42O5.jpg {/dede:img}
