<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/2016-05/15152551-1-19294.jpg ",93,202);
$z[1][4]['ddimg']="";
$z[1][4]['text']="";
$z[1][4]['width']="978";
$z[1][4]['height']="619";
$z[2]=Array("img"," /uploads/allimg/2016-05/15152551-1-29194.jpg ",204,313);
$z[2][4]['ddimg']="";
$z[2][4]['text']="";
$z[2][4]['width']="978";
$z[2][4]['height']="619";
$z[3]=Array("img"," /uploads/allimg/2016-05/15152551-1-35247.jpg ",315,424);
$z[3][4]['ddimg']="";
$z[3][4]['text']="";
$z[3][4]['width']="978";
$z[3][4]['height']="619";
$z[4]=Array("img"," /uploads/allimg/2016-05/15152551-1-42O5.jpg ",426,534);
$z[4][4]['ddimg']="";
$z[4][4]['text']="";
$z[4][4]['width']="978";
$z[4][4]['height']="619";

?>