<?php
$z[0]=Array("global","",33,62);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("global","",107,134);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",134,159);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",376,403);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("global","",403,428);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("global","",559,586);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",586,611);
$z[6][4]['name']="cfg_cmsurl";

?>