<li>
				<a  href="[field:linkurl/]">
					
					<img src="[field:cover_img/] " width="202px" height="317px"/>
				</a>
				<div class="erwei">
					
					<img src="[field:erwei_img/] " width="170" />	
				</div>
				<h2>[field:title /]</h2>
				<div style=" border: 1px dashed #937344;
    color: #937344;
    display: block;
    font-size: 14px;
    line-height: 24px;
    margin: 15px auto 0;
    text-align: center;
    width: 90px;"><a href="[field:linkurl/]" title="[field:fulltitle /] " class="btn_video">点xxx阅</a></div>
			</li>