<a href='[field:arcurl/]'>[field:title/]</a>


<div class="ctablk news ">
	<div class="wr">
		<div class="container trans">
			<a class="homenewslink" href="[field:arcurl/]">
				<div class="georgia-title">
					<h3>
						<div style="margin: 0px; padding: 0px; border: 0px none;">[field:title/]</div>
					</h3> <i class="sprite-h gtitle-deco below"></i>
				</div>
				<p>[field:description/]</p>
				<div class="cta">
					<div>
						<span class="label">阅读</span>
					</div>
				</div>
				<div class="visu">
					<img src="[field:picname/]"  style="display: inline;width:289px;height:180px"></div>
			</a>
		</div>
	</div>
</div>