<?php
$z[0]=Array("field","",4,33);
$z[0][4]['name']="typename";
$z[1]=Array("list","\r\n			<li>\r\n				<a  href=\"[field:linkurl/]\">\r\n					<!--  封面  -->\r\n					<img src=\"[field:cover_img/] \" width=\"202px\" height=\"317px\"/>	\r\n				</a>\r\n				<div class=\"erwei\">\r\n					<!-- 二维码图片 -->\r\n					<img src=\"[field:erwei_img/] \" width=\"170\" />	\r\n				</div>\r\n				<h2>[field:title /]</h2>\r\n				<a href=\"[field:arcurl/]\" title=\"[field:fulltitle /] \" class=\"btn_video\">点阅</a>\r\n			</li>\r\n		",70,525);
$z[1][4]['addfields']="jiage";
$z[1][4]['channelid']="2";

?>