<div class="tsfw_list">
    <div class="tsfw_list_left">
      <a href="[field:zt_linkurl/]"><img src="[field:picname/]" width="350" height="240" /></a>
    </div>
    <div class="tsfw_list_right">
      <div class="right_tm">
	    <p><a href="[field:zt_linkurl/]">[field:title/]</a></p>
	    <p>[field:infos/]</p>
	  </div>
	  <div class="right_zx">
	    <ul>
	      <li><a href="[field:arcurl/]">了解详情</a></li>
	      <li><a href="http://pdt.zoosnet.net/LR/Chatpre.aspx?id=PDT21034666&lng=cn">在线咨询</a></li>
	      <li><a href="http://pdt.zoosnet.net/LR/Chatpre.aspx?id=PDT21034666&lng=cn">预约挂号</a></li>
	    </ul>
	  </div>
    </div>
  </div>