<?php
$z[0]=Array("global","",210,242);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",4197,4229);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",4443,4475);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",4836,4868);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",5128,5160);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",5310,5337);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",5337,5364);
$z[6][4]['name']="cfg_indexurl";

?>