<?php
$z[0]=Array("global","",210,242);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("channelartlist","\r\n				<a href='{dede:field name='typeurl'/}' target=\"_blank\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a>\r\n				",457,650);
$z[1][4]['typeid']="4";
$z[2]=Array("global","",3620,3652);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",3866,3898);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",4194,4226);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",4486,4518);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",4668,4695);
$z[6][4]['name']="cfg_basehost";
$z[7]=Array("global","",4695,4722);
$z[7][4]['name']="cfg_indexurl";

?>