<?php
$z[0]=Array("global","",12,44);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",108,140);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",183,215);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",282,314);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",386,418);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",520,552);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",635,667);
$z[6][4]['name']="cfg_templets_skin";

?>