<?php
$z[0]=Array("global","",177,203);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",248,278);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",316,343);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",394,426);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",500,532);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",563,595);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",683,715);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("include","",882,919);
$z[7][4]['filename']="header.htm";
$z[8]=Array("arclist","\r\n<div class=\"ctablk news \">\r\n	<div class=\"wr\">\r\n		<div class=\"container trans first\">\r\n			<a class=\"homenewslink\" href=\"[field:arcurl/]\">\r\n				<div class=\"georgia-title\">\r\n					<h3>\r\n						<div style=\"margin: 0px; padding: 0px; border: 0px none;\">[field:title/]</div>\r\n					</h3> <i class=\"sprite-h gtitle-deco below\"></i>\r\n				</div>\r\n				<p>[field:description/]</p>\r\n				<div class=\"cta\">\r\n					<div>\r\n						<span class=\"label\">阅读</span>\r\n					</div>\r\n				</div>\r\n				<div class=\"visu\">\r\n					<img src=\"[field:picname/]\"  style=\"display: inline;width:289px;height:180px\"></div>\r\n			</a>\r\n		</div>\r\n	</div>\r\n</div>\r\n\r\n",7775,8451);
$z[8][4]['typeid']="45";
$z[8][4]['row']="4";
$z[9]=Array("include","",8630,8667);
$z[9][4]['filename']="footer.htm";

?>