<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",379,416);
$z[2][4]['filename']="header.htm";
$z[3]=Array("field","",589,611);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n<dd><a href='[field:typelink/]'>[field:typename/]</a></dd>\r\n",657,772);
$z[4][4]['type']="son";
$z[4][4]['typeid']="609";
$z[5]=Array("channelartlist","\r\n<li>\r\n<div class=\"keshi_list_pic\"><img src=\"/templets/dzsjyy/new/keshipic/{dede:field name='typeid'/}.jpg\"></div>\r\n<div class=\"keshi_tit\">{dede:field name='typename'/}<a href=\"{dede:field name='typeurl'/}\">了解更多</a></div>\r\n<div class=\"keshi_art\">{dede:arclist titlelen='18'}<dd><a href=\"[field:arcurl /]\">[field:title /]</a></dd>{/dede:arclist}</div>\r\n</li>\r\n",1130,1554);
$z[5][4]['typeid']="614";
$z[6]=Array("channelartlist","\r\n<li>\r\n<div class=\"keshi_list_pic\"><img src=\"/templets/dzsjyy/new/keshipic/{dede:field name='typeid'/}.jpg\"></div>\r\n<div class=\"keshi_tit\">{dede:field name='typename'/}<a href=\"{dede:field name='typeurl'/}\">了解更多</a></div>\r\n<div class=\"keshi_art\">{dede:arclist titlelen='18'}<dd><a href=\"[field:arcurl /]\">[field:title /]</a></dd>{/dede:arclist}</div>\r\n</li>\r\n",1603,2027);
$z[6][4]['typeid']="615";
$z[7]=Array("channelartlist","\r\n<li>\r\n<div class=\"keshi_list_pic\"><img src=\"/templets/dzsjyy/new/keshipic/{dede:field name='typeid'/}.jpg\"></div>\r\n<div class=\"keshi_tit\">{dede:field name='typename'/}<a href=\"{dede:field name='typeurl'/}\">了解更多</a></div>\r\n<div class=\"keshi_art\">{dede:arclist titlelen='18'}<dd><a href=\"[field:arcurl /]\">[field:title /]</a></dd>{/dede:arclist}</div>\r\n</li>\r\n",2076,2500);
$z[7][4]['typeid']="616";
$z[8]=Array("channelartlist","\r\n<li>\r\n<div class=\"keshi_list_pic\"><img src=\"/templets/dzsjyy/new/keshipic/{dede:field name='typeid'/}.jpg\"></div>\r\n<div class=\"keshi_tit\">{dede:field name='typename'/}<a href=\"{dede:field name='typeurl'/}\">了解更多</a></div>\r\n<div class=\"keshi_art\">{dede:arclist titlelen='18'}<dd><a href=\"[field:arcurl /]\">[field:title /]</a></dd>{/dede:arclist}</div>\r\n</li>\r\n",2549,2973);
$z[8][4]['typeid']="617";
$z[9]=Array("channelartlist","\r\n<li>\r\n<div class=\"keshi_list_pic\"><img src=\"/templets/dzsjyy/new/keshipic/{dede:field name='typeid'/}.jpg\"></div>\r\n<div class=\"keshi_tit\">{dede:field name='typename'/}<a href=\"{dede:field name='typeurl'/}\">了解更多</a></div>\r\n<div class=\"keshi_art\">{dede:arclist titlelen='18'}<dd><a href=\"[field:arcurl /]\">[field:title /]</a></dd>{/dede:arclist}</div>\r\n</li>\r\n",3022,3446);
$z[9][4]['typeid']="618";
$z[10]=Array("include","",3983,4020);
$z[10][4]['filename']="footer.htm";

?>