<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",379,417);
$z[2][4]['filename']="header2.htm";
$z[3]=Array("field","\r\nif(@me == 614){\r\n@me = 'weichuang';\r\n}\r\nif(@me == 615){\r\n@me = 'zhushe';\r\n}\r\nif(@me == 616){\r\n@me = 'pifu';\r\n}\r\nif(@me == 617){\r\n@me = 'zhongyi';\r\n}\r\nif(@me == 618){\r\n@me = 'wenxiu';\r\n}\r\n",513,754);
$z[3][4]['name']="typeid";
$z[3][4]['runphp']="yes";
$z[4]=Array("field","",921,943);
$z[4][4]['name']="typename";
$z[5]=Array("channel","\r\n<dd><a href='[field:typelink/]'>[field:typename/]</a></dd>\r\n",989,1104);
$z[5][4]['type']="son";
$z[5][4]['typeid']="609";
$z[6]=Array("channelartlist","\r\n<li>\r\n<div class=\"keshi_list_pic\"><img src=\"/templets/dzsjyy/new/keshipic/{dede:field name='typeid'/}.jpg\"></div>\r\n<div class=\"keshi_tit\">{dede:field name='typename'/}<a href=\"{dede:field name='typeurl'/}\">了解更多</a></div>\r\n<div class=\"keshi_art\">{dede:arclist titlelen='18'}<dd><a href=\"[field:arcurl /]\">[field:title /]</a></dd>{/dede:arclist}</div>\r\n</li>\r\n",1745,2156);
$z[7]=Array("field","",2248,2268);
$z[7][4]['name']="typeid";
$z[8]=Array("field","",2317,2337);
$z[8][4]['name']="typeid";
$z[9]=Array("include","",2423,2460);
$z[9][4]['filename']="footer.htm";

?>