<?php
$z[0]=Array("field","",173,192);
$z[0][4]['name']="title";
$z[1]=Array("global","",193,219);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",260,289);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",329,387);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",438,470);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",512,544);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","",803,840);
$z[6][4]['filename']="header.htm";
$z[7]=Array("global","",929,958);
$z[7][4]['name']="cfg_medias_dir";
$z[8]=Array("arclist","\r\n\r\n		<li>\r\n			<a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\"><img src=\"[field:picname/]\" width=\"200px\" height=\"150px\"/></a>\r\n			<h2>[field:title/]</h2>\r\n		\r\n			<a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\" class=\"btn_video\">查看</a>\r\n		</li>\r\n\r\n		",1237,1574);
$z[8][4]['infolen']="100";
$z[8][4]['imgwidth']="200";
$z[8][4]['imgheight']="150";
$z[9]=Array("include","",1679,1716);
$z[9][4]['filename']="footer.htm";

?>