<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",387,424);
$z[2][4]['filename']="header.htm";
$z[3]=Array("field","",593,615);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n<dd><a href='[field:typelink/]'>[field:typename/]</a></dd>\r\n",661,776);
$z[4][4]['type']="son";
$z[4][4]['typeid']="609";
$z[5]=Array("arclist","\r\n  <div class=\"tsfw_list\">\r\n    <div class=\"tsfw_list_left\">\r\n      <a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" width=\"350\" height=\"240\" /></a>\r\n    </div>\r\n    <div class=\"tsfw_list_right\">\r\n      <div class=\"right_tm\">\r\n	    <p><a href=\"[field:arcurl/]\">[field:fulltitle/]</a></p>\r\n	    <p>[field:infos/]</p>\r\n	  </div>\r\n	  <div class=\"right_zx\">\r\n	    <ul>\r\n	      <li><a href=\"[field:arcurl/]\">了解详情</a></li>\r\n	      <li><a href=\"http://pdt.zoosnet.net/LR/Chatpre.aspx?id=PDT21034666&lng=cn\">在线咨询</a></li>\r\n	      <li><a href=\"http://pdt.zoosnet.net/LR/Chatpre.aspx?id=PDT21034666&lng=cn\">预约挂号</a></li>\r\n	    </ul>\r\n	  </div>\r\n    </div>\r\n  </div>\r\n",883,1599);
$z[6]=Array("include","",1640,1677);
$z[6][4]['filename']="footer.htm";

?>