<?php
$z[0]=Array("field","",177,196);
$z[0][4]['name']="title";
$z[1]=Array("global","",197,223);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",265,294);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",335,393);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",447,479);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",554,586);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",618,650);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",739,771);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",853,885);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("include","",1054,1091);
$z[9][4]['filename']="header.htm";
$z[10]=Array("list","\r\n\r\n				<li class=\"con_slider1\">\r\n					<a href=\"[field:arcurl/]\" target=\"_blank\">\r\n						<img src=\"[field:doctor_img/]\"/>			\r\n					</a>\r\n				</li>\r\n\r\n ",1919,2107);
$z[10][4]['pagesize']="10";
$z[11]=Array("list","\r\n	<li>\r\n		<div class=\"left ic_img\">\r\n			<img src=\"[field:picname/]\"/>	\r\n		</div>\r\n		<div class=\"left ic_desc\">\r\n			<div class=\"item_nav_tit\">\r\n				<h1>[field:title/]</h1>\r\n				<p>[field:description/]</p>\r\n			</div>\r\n			<a href=\"[field:arcurl/]\" target=\"_blank\" class=\"btn_box\">更多详情</a>\r\n		</div>\r\n\r\n		<div class=\"clear\"></div>\r\n	</li>\r\n ",2459,2828);
$z[12]=Array("include","",3222,3259);
$z[12][4]['filename']="footer.htm";

?>