<?php
$z[0]=Array("field","",173,192);
$z[0][4]['name']="title";
$z[1]=Array("global","",193,219);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",260,289);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",329,387);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",438,470);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",544,576);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",607,639);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",727,759);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("include","",1007,1044);
$z[8][4]['filename']="header.htm";
$z[9]=Array("arclist","\r\n				<li class=\"con_slider1\">\r\n\r\n					<a href=\"[field:arcurl/]\" target=\"_blank\">\r\n						<img src='[field:banner_img/]'></i>\r\n						<span>[field:title/]</span>\r\n					</a>\r\n				</li>\r\n				",1416,1671);
$z[9][4]['addfields']="banner_img";
$z[9][4]['channelid']="20";
$z[10]=Array("arclist","\r\n				<li>\r\n					<div class='left ic_desc'>\r\n						<div class=\"item_nav_tit\">\r\n							<h1>[field:title/]</h1>\r\n							<span></span>\r\n							<span>蝶变感受：</span>\r\n							<p>[field:description/]</p>\r\n						</div>\r\n						<a href=\"[field:arcurl/]\" target=\"_blank\" class=\"btn_box\">更多详情</a>\r\n					</div>\r\n					<div class=\"right ic_img\">\r\n						<img src=\"[field:picname/]\"  width=\"600px\" height=\"635px\"/>				\r\n					</div>\r\n					<div class=\"clear\"></div>\r\n				</li>\r\n	",1772,2277);
$z[11]=Array("include","",2662,2699);
$z[11][4]['filename']="footer.htm";

?>