<?php
$z[0]=Array("global","",262,294);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",355,387);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",452,484);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",541,573);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",628,660);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",716,748);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",11657,11689);
$z[6][4]['name']="cfg_templets_skin";

?>