<?php
$z[0]=Array("global","",340,372);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",433,465);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",530,562);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",627,659);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",738,770);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",826,858);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("arclist","\r\n				  <li><a href=\"[field:arcurl /]\" target=\"_blank\">[field:title /]</a></li>\r\n				  ",3157,3285);
$z[6][4]['typeid']="13";
$z[7]=Array("arclist","\r\n				  <li><a href=\"[field:arcurl /]\" target=\"_blank\">[field:title /]</a></li>\r\n				  ",3784,3912);
$z[7][4]['typeid']="14";
$z[8]=Array("arclist","\r\n				  <li><a href=\"[field:arcurl /]\" target=\"_blank\">[field:title /]</a></li>\r\n				  ",4411,4539);
$z[8][4]['typeid']="15";
$z[9]=Array("arclist","\r\n				  <li><a href=\"[field:arcurl /]\" target=\"_blank\">[field:title /]</a></li>\r\n				  ",5038,5166);
$z[9][4]['typeid']="16";
$z[10]=Array("arclist","\r\n				  <li><a href=\"[field:arcurl /]\" target=\"_blank\">[field:title /]</a></li>\r\n				  ",5665,5793);
$z[10][4]['typeid']="17";
$z[11]=Array("global","",6218,6250);
$z[11][4]['name']="cfg_templets_skin";
$z[12]=Array("global","",6304,6336);
$z[12][4]['name']="cfg_templets_skin";
$z[13]=Array("global","",6437,6469);
$z[13][4]['name']="cfg_templets_skin";
$z[14]=Array("global","",7947,7979);
$z[14][4]['name']="cfg_templets_skin";

?>